package main

func SupportedDataTypes() []string {
	return []string{
		"int8,",
		"bigserial,",
		"int,",
		"smallint,",
		"smallserial,",
		"serial,",
		"float4,",
		"float8,",
		"numeric(4,2),",
		"bit,",
		"varbit(4),",
		"bool,",
		"char(10),",
		"varchar(10),",
		"text,",
		"inet,",
		"macaddr,",
		"cidr,",
		"interval,",
		"date,",
		"time without time zone,",
		"time with time zone,",
		"timestamp with time zone,",
		"timestamp without time zone,",
		"money,",
		"json,",
		"jsonb,",
		"xml,",
		"tsquery,",
		"tsvector,",
		"box,",
		"circle,",
		"line,",
		"lseg,",
		"path,",
		"polygon,",
		"point,",
		"bytea,",
		"pg_lsn,",
		"txid_snapshot,",
		"uuid,",
		"smallint[],",
		"int[],",
		"bigint[],",
		"char(10)[],",
		"varchar(10)[],",
		"bit(10)[],",
		"varbit(4)[],",
		"numeric[],",
		"numeric(5,3)[],",
		"float4[],",
		"float8[],",
		"money[],",
		"time without time zone[],",
		"interval[],",
		"date[],",
		"time with time zone[],",
		"timestamp with time zone[],",
		"timestamp without time zone[],",
		"text[],",
		"bool[],",
		"inet[],",
		"macaddr[],",
		"cidr[],",
		"uuid[],",
		"txid_snapshot[],",
		"pg_lsn[],",
		"tsquery[],",
		"tsvector[],",
		"box[],",
		"circle[],",
		"line[],",
		"lseg[],",
		"path[],",
		"polygon[],",
		"point[],",
		"json[],",
		"jsonb[],",
		"xml[],",
	}
}
