CREATE TABLE sample_255_col (
     sample_col_1 smallint NOT NULL,
     sample_col_2 integer NOT NULL,
     sample_col_3 integer NOT NULL,
     sample_col_4 date NOT NULL,
     sample_col_5 date NOT NULL,
     sample_col_6 character varying(1) NOT NULL,
     sample_col_7 timestamp without time zone NOT NULL,
     sample_col_8 date,
     sample_col_9 smallint,
     sample_col_10 smallint,
     sample_col_11 date,
     sample_col_12 numeric(13,2),
     sample_col_13 numeric(13,2),
     sample_col_14 smallint,
     sample_col_15 date,
     sample_col_16 date,
     sample_col_17 smallint,
     sample_col_18 timestamp without time zone NOT NULL,
     sample_col_19 smallint,
     sample_col_20 smallint,
     sample_col_21 numeric(13,2),
     sample_col_22 numeric(5,2),
     sample_col_23 character varying(1),
     sample_col_24  date,
     sample_col_25 time without time zone NOT NULL,
     sample_col_26 character varying(1),
     sample_col_27 numeric(11,2),
     sample_col_28 character varying(1),
     sample_col_29 character varying(4) NOT NULL,
     sample_col_30 date NOT NULL,
     sample_col_31 time without time zone NOT NULL,
     sample_col_32 character varying(8) NOT NULL,
     sample_col_33 character varying(1) NOT NULL,
     sample_col_34 numeric(6,4) NOT NULL,
     sample_col_35 smallint NOT NULL,
     sample_col_36 smallint,
     sample_col_37 character varying(1) NOT NULL,
     sample_col_38 integer NOT NULL,
     sample_col_39 integer NOT NULL,
     sample_col_40 integer NOT NULL,
     sample_col_41 integer NOT NULL,
     sample_col_42 numeric(11,2),
     sample_col_43 character varying(1),
     sample_col_44 integer NOT NULL,
     sample_col_45 integer NOT NULL,
     sample_col_46 integer NOT NULL,
     sample_col_47 character varying(30) NOT NULL,
     sample_col_48 character varying(10) NOT NULL,
     sample_col_49 character varying(8) NOT NULL,
     sample_col_50 character varying(1) NOT NULL,
     sample_col_51 character varying(20) NOT NULL,
     sample_col_52 character varying(45) NOT NULL,
     sample_col_53 character varying(1),
     sample_col_54 character varying(1),
     sample_col_55 integer,
     sample_col_56 character varying(20) NOT NULL,
     sample_col_57 character varying(30) NOT NULL,
     sample_col_58 character varying(10) NOT NULL,
     sample_col_59 character varying(8) NOT NULL,
     sample_col_60 character varying(30) NOT NULL,
     sample_col_61 character varying(10) NOT NULL,
     sample_col_62 character varying(8) NOT NULL,
     sample_col_63 character varying(20) NOT NULL,
     sample_col_64 character varying(10),
     sample_col_65 time without time zone NOT NULL,
     sample_col_66 character varying(3),
     sample_col_67 character varying(1),
     sample_col_68 character varying(1) NOT NULL,
     sample_col_69 integer,
     sample_col_70 numeric(13,2) NOT NULL,
     sample_col_71 character varying(1),
     sample_col_72 character varying(1),
     sample_col_73 smallint,
     sample_col_74 smallint,
     sample_col_75 character varying(1) NOT NULL,
     sample_col_76 integer NOT NULL,
     sample_col_77 integer NOT NULL,
     sample_col_78 character varying(2) NOT NULL,
     sample_col_79 character varying(1),
     sample_col_80 character varying(1) NOT NULL,
     sample_col_81 numeric(11,2) NOT NULL,
     sample_col_82 character varying(1),
     sample_col_83 numeric(5,2) NOT NULL,
     sample_col_84 character varying(6) NOT NULL,
     sample_col_85 character varying(15) NOT NULL,
     sample_col_86 character varying(3) NOT NULL,
     sample_col_87 character varying(1) NOT NULL,
     sample_col_88 smallint NOT NULL,
     sample_col_89 smallint NOT NULL,
     sample_col_90 character varying(1) NOT NULL,
     sample_col_91 character varying(1) NOT NULL,
     sample_col_92 character varying(1),
     sample_col_93 integer,
     sample_col_94 character varying(6) NOT NULL,
     sample_col_95 character varying(1),
     sample_col_96 character varying(1) NOT NULL,
     sample_col_97 character varying(25) NOT NULL,
     sample_col_98 character varying(25) NOT NULL,
     sample_col_99 numeric(11,2),
     sample_col_100 character varying(1),
     sample_col_101 character varying(1),
     sample_col_102 smallint,
     sample_col_103 smallint,
     sample_col_104 smallint,
     sample_col_105 date NOT NULL,
     sample_col_106 date NOT NULL,
     sample_col_107 character varying(1),
     sample_col_108 character varying(1) NOT NULL,
     sample_col_109 character varying(1) NOT NULL,
     sample_col_110 smallint,
     sample_col_111 date,
     sample_col_112 character varying(1) NOT NULL,
     sample_col_113 bigint,
     sample_col_114 character varying(1),
     sample_col_115 character varying(1) NOT NULL,
     sample_col_116 character varying(1) NOT NULL,
     sample_col_117 smallint NOT NULL,
     sample_col_118 smallint NOT NULL,
     sample_col_119 smallint NOT NULL,
     sample_col_120 character varying(1) NOT NULL,
     sample_col_121 character varying(1),
     sample_col_122 integer,
     sample_col_123 integer,
     sample_col_124 smallint NOT NULL,
     sample_col_125 character varying(1) NOT NULL,
     sample_col_126 numeric(5,2) NOT NULL,
     sample_col_127 smallint,
     sample_col_128 character varying(1) NOT NULL,
     sample_col_129 character varying(25) NOT NULL,
     sample_col_130 character varying(1),
     sample_col_131 character varying(11) NOT NULL,
     sample_col_132 character varying(1) NOT NULL,
     sample_col_133 character varying(1),
     sample_col_134 character varying(1),
     sample_col_135 character varying(1) NOT NULL,
     sample_col_136 numeric(10,2) NOT NULL,
     sample_col_137 numeric(10,2) NOT NULL,
     sample_col_138 numeric(13,2),
     sample_col_139 numeric(10,2) NOT NULL,
     sample_col_140 character varying(1) NOT NULL,
     sample_col_141 character varying(4),
     sample_col_142 character varying(1),
     sample_col_143 character varying(1) NOT NULL,
     sample_col_144 smallint,
     sample_col_145 character varying(1),
     sample_col_146 smallint NOT NULL,
     sample_col_147 character varying(1) NOT NULL,
     sample_col_148 character varying(1) NOT NULL,
     sample_col_149 character varying(1),
     sample_col_150 character varying(5) NOT NULL,
     sample_col_151 character varying(5) NOT NULL,
     sample_col_152 character varying(1) NOT NULL,
     sample_col_153 character varying(1) NOT NULL,
     sample_col_154 character varying(1),
     sample_col_155 character varying(1),
     sample_col_156 smallint NOT NULL,
     sample_col_157 date,
     sample_col_158 character varying(2) NOT NULL,
     sample_col_159 character varying(1) NOT NULL,
     sample_col_160 character varying(1),
     sample_col_161 numeric(13,2),
     sample_col_162 smallint NOT NULL,
     sample_col_163 character varying(1),
     sample_col_164 character varying(2) NOT NULL,
     sample_col_165 smallint NOT NULL,
     sample_col_166 character varying(1) NOT NULL,
     sample_col_167 character varying(1) NOT NULL,
     sample_col_168 character varying(4),
     sample_col_169 character varying(2),
     sample_col_170 character varying(1) NOT NULL,
     sample_col_171 character varying(1) NOT NULL,
     sample_col_172 numeric(6,4) NOT NULL,
     sample_col_173 smallint NOT NULL,
     sample_col_174 character varying(8),
     sample_col_175 character varying(7),
     sample_col_176 smallint NOT NULL,
     sample_col_177 character varying(15) NOT NULL,
     sample_col_178 character varying(1) NOT NULL,
     sample_col_179 numeric(5,2) NOT NULL,
     sample_col_180 character varying(4) NOT NULL,
     sample_col_181 smallint NOT NULL,
     sample_col_182 character varying(6) NOT NULL,
     sample_col_183 integer NOT NULL,
     sample_col_184 character varying(1),
     sample_col_185 bigint,
     sample_col_186 numeric(11,2),
     sample_col_187 character varying(1) NOT NULL,
     sample_col_188 character varying(1) NOT NULL,
     sample_col_189 character varying(1) NOT NULL,
     sample_col_190 character varying(12) NOT NULL,
     sample_col_191 character varying(2) NOT NULL,
     sample_col_192 character varying(1) NOT NULL,
     sample_col_193 character varying(1),
     sample_col_194 smallint,
     sample_col_195 character varying(1),
     sample_col_196 smallint NOT NULL,
     sample_col_197 character varying(1),
     sample_col_198 character varying(36),
     sample_col_199 character varying(3),
     sample_col_200 bigint,
     sample_col_201 bigint NOT NULL,
     sample_col_202 bigint NOT NULL,
     sample_col_203 bigint NOT NULL,
     sample_col_204 character varying(1) NOT NULL,
     sample_col_205 character varying(1) NOT NULL,
     sample_col_206 character varying(20),
     sample_col_207 character varying(1) NOT NULL,
     sample_col_208 smallint,
     sample_col_209 character varying(1) NOT NULL,
     sample_col_210 date,
     sample_col_211 smallint,
     sample_col_212 smallint,
     sample_col_213 numeric(13,2),
     sample_col_214 smallint,
     sample_col_215 numeric(13,2),
     sample_col_216 smallint,
     sample_col_217 smallint,
     sample_col_218 character varying(1),
     sample_col_219 numeric(5,2),
     sample_col_220 smallint,
     sample_col_221 numeric(13,2),
     sample_col_222 smallint,
     sample_col_223 smallint,
     sample_col_224 date,
     sample_col_225 smallint NOT NULL,
     sample_col_226 smallint,
     sample_col_227 smallint,
     sample_col_228 integer,
     sample_col_229 date,
     sample_col_230 integer,
     sample_col_231 date,
     sample_col_232 integer,
     sample_col_233 date,
     sample_col_234 date,
     sample_col_235 timestamp without time zone,
     sample_col_236 date,
     sample_col_237 timestamp without time zone,
     sample_col_238 integer,
     sample_col_239 date,
     sample_col_240 integer,
     sample_col_241 date,
     sample_col_242 integer,
     sample_col_243 date,
     sample_col_244 integer,
     sample_col_245 date,
     sample_col_246 integer,
     sample_col_247 date,
     sample_col_248 integer,
     sample_col_249 date,
     sample_col_250 integer,
     sample_col_251 date,
     sample_col_252 integer,
     sample_col_253 date,
     sample_col_254 integer,
     sample_col_255 date
);
